export default {
  platform: 'YouTube',
  uid: 'ZPxuohy5SoU',
  prereqs: [
    'I know Python to some extent.',
    'I know data science and ETL to some extent.',
  ],
  outcomes: [
    'I know how to use Kedro in a basic way.',
  ],
  modules: [
    {
	  index: 0,
      name: 'Intro: Tom Goldenberg',
      start: 29,
      end: 116,
      outcome: 'know who Tom Goldenberg is',
    },
    {
	  index: 1,
      name: 'Intro: QuantumBlack',
      start: 116,
      end: 177,
      outcome: 'know something about QuantumBlack',
    },
    {
	  index: 2,
      name: 'Intro: Agenda',
      start: 177,
      end: 242,
      outcome: 'know what the agenda is',
    },
    {
	  index: 3,
      name: 'Intro: Kedro',
      start: 242,
      end: 523,
      outcome: 'know what Kedro is',
    },
    {
	  index: 4,
      name: 'Intro: kedro-viz',
      start: 523,
      end: 558,
      outcome: 'know what kedro-viz is',
    },
    {
	  index: 5,
      name: 'Intro: MLFlow',
      start: 558,
      end: 871,
      outcome: 'know what MLFlow is',
    },
    {
	  index: 6,
      name: 'installing Kedro and prereqs',
      start: 871,
      end: 939,
      outcome: 'have pandas/conda and kedro installed',
    },
    {
	  index: 7,
      name: 'create a virtual environment',
      start: 939,
      end: 1038,
      outcome: 'have an activated virtual environment for playing with kedro (`kedro info` produces something)',
    },
    {
	  index: 8,
      name: 'create a kedro project',
      start: 1038,
      end: 1175,
      outcome: 'create a new kedro project',
    },
  ],
};
